### ISSUE TITLE
Selector finds deleted objects and states of deleted objects still exist

### ISSUE THREAD

**Issue by qokaface** [ioBroker/ioBroker.javascript#185] opened 2018-09-26 19:59 UTC
Dear developers,

An object (alexa2 alarm) is deleted and hence doesn't appear in the object tree anymore. Nevertheless, the selector $(...) still finds the ID of this object and the state still exists. Restarting the javascript adapter solves the problem.

See: https://forum.iobroker.net/viewtopic.php?f=37&t=17210 for log output and German description of the behavior.

Best regards and thank you in advance,
qokaface

**Comment by AlCalzone** [comment] 2018-09-27 16:42
I found that behavior a while ago when reworking the selector function. However it wasn’t entirely clear how to best solve this, so I left it as is.
I’m working on a larger refactoring of the adapter structure and this is something I want to solve while doing so.

**Comment by AlCalzone** [comment] 2019-02-28 13:36
I now think this is a duplicate of #109

**Closed** 2019-02-28 15:35 UTC
Labels: bug, duplicate
