### ISSUE TITLE
Update to adapter version 5.2.11 is not successful 

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.javascript#880] opened 2021-09-11 19:27 UTC
Admin 5.1.25
Javascript Adapter 5.2.10 to 5.2.11

Bug:
After successful update the adapter from 5.2.10 to 5.2.11 in Admin menu the update to 5.2.11 is still shown. 
Shell command "iobroker list adapters" shows that version 5.2.10 is still installed and not 5.2.11

Steps to reproduce
- Update javascript adapter to 5.2.11
- Updateable Adapter is still shown but without changelog
- ![grafik](https://user-images.githubusercontent.com/25422320/132959178-01427409-b2c8-4af8-9cc4-cb48bbcbc93b.png)
- iobroker update still shows
-- ![grafik](https://user-images.githubusercontent.com/25422320/132959224-f64a6ad5-3896-4107-9ac2-a685912e8cda.png)

Log from update 5.2.10 to 5.2.11

```
$ iobroker upgrade javascript@5.2.11

Update javascript from @5.2.10 to @5.2.11

NPM version: 6.14.14

npm install iobroker.javascript@5.2.11 --loglevel error --prefix "/opt/iobroker" (System call)

Update "system.adapter.javascript.0"

upload [100] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/typescript/tsWorker.js vs/language/typescript/tsWorker.js application/javascript

upload [90] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.js vs/editor/editor.main.nls.js application/javascript

upload [80] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/basic-languages/javascript/javascript.js vs/basic-languages/javascript/javascript.js application/javascript

upload [70] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/js/main.8e727556.chunk.js static/js/main.8e727556.chunk.js application/javascript

upload [60] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/index_m.html index_m.html text/html

upload [50] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/own/msg/de.js google-blockly/own/msg/de.js application/javascript

upload [40] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/own/blocks_sendto.js google-blockly/own/blocks_sendto.js application/javascript

upload [30] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/msg/js/it.js google-blockly/msg/js/it.js application/javascript

upload [20] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/handopen.cur google-blockly/media/handopen.cur null

upload [19] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/handdelete.cur google-blockly/media/handdelete.cur null

upload [18] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/handclosed.cur google-blockly/media/handclosed.cur null

upload [17] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/dropdown-arrow.svg google-blockly/media/dropdown-arrow.svg image/svg+xml

upload [16] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/disconnect.wav google-blockly/media/disconnect.wav audio/wav

upload [15] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/disconnect.ogg google-blockly/media/disconnect.ogg audio/ogg

upload [14] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/disconnect.mp3 google-blockly/media/disconnect.mp3 audio/mpeg

upload [13] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/delete.wav google-blockly/media/delete.wav audio/wav

upload [12] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/delete.ogg google-blockly/media/delete.ogg audio/ogg

upload [11] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/delete.mp3 google-blockly/media/delete.mp3 audio/mpeg

upload [10] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/click.wav google-blockly/media/click.wav audio/wav

upload [9] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/click.ogg google-blockly/media/click.ogg audio/ogg

upload [8] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/click.mp3 google-blockly/media/click.mp3 audio/mpeg

upload [7] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/1x1.gif google-blockly/media/1x1.gif image/gif

upload [6] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/javascript_compressed.js google-blockly/javascript_compressed.js application/javascript

upload [5] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/blocks_compressed.js google-blockly/blocks_compressed.js application/javascript

upload [4] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/blockly_compressed.js google-blockly/blockly_compressed.js application/javascript

upload [3] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/LICENSE google-blockly/LICENSE null

upload [2] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/favicon.ico favicon.ico image/vnd.microsoft.icon

upload [1] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/asset-manifest.json asset-manifest.json application/json

upload [0] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/adminWords.js adminWords.js application/javascript

Adapter "javascript" updated

Process exited with code 0
```

**Comment by DutchmanNL** [comment] 2021-09-11 20:53
Version in io-package is wrong 

https://github.com/ioBroker/ioBroker.javascript/blob/master/io-package.json#L23

**Comment by BramTown** [comment] 2021-09-11 23:19
additonally I get interesting Log-Entries
`
<pre class="markdown-highlight" style="box-sizing: border-box; overflow: auto; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; font-size: 13px; display: block; padding: 9.5px; margin: 1rem 0px 10px; line-height: 1.42857; word-break: break-all; overflow-wrap: break-word; color: rgb(51, 51, 51); background-color: rgb(255, 255, 255); border: none; border-radius: 0px; max-height: 350px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code class="hljs perl" data-lines="1" style="box-sizing: border-box; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; font-size: inherit; padding: 0.5em; color: rgb(230, 225, 220); background: rgb(35, 35, 35); border-radius: 0px; white-space: pre; display: inline-block; overflow-x: auto; overflow-wrap: normal; min-width: 100%;">

avascript.0
--
  | 2021-09-12 00:03:41.982	error	axios-cookiejar-support@1.0.1 requires a peer of @types/tough-cookie@>=2.3.3 but none is installed. You must install peer dependencies yourself.
  | javascript.0
  | 2021-09-12 00:03:39.548	error	deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
  | javascript.0
  | 2021-09-12 00:03:37.230	error	deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
  | javascript.0
  | 2021-09-12 00:03:37.124	error	deprecated har-validator@5.1.5: this library is no longer supported
  | 2021-09-12 00:03:36.884	error	WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  | javascript.0
  | 2021-09-12 00:03:35.174	error	WARN axios-cookiejar-support@1.0.1 requires a peer of @types/tough-cookie@>=2.3.3 but none is installed. You must install peer dependencies yourself.
  | javascript.0
  | 2021-09-12 00:03:32.003	error	WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

</code></pre><br class="Apple-interchange-newline">`

**Comment by vepman** [comment] 2021-09-12 08:51
Bei mir wird das Update auch nicht ausgeführt:
  
`$ ./iobroker upgrade javascript
Update javascript from @5.2.10 to @5.2.11
NPM version: 6.14.15
npm install iobroker.javascript@5.2.11 --loglevel error --prefix "/opt/iobroker" (System call)
Update "system.adapter.javascript.0"
upload [100] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/language/typescript/tsWorker.js vs/language/typescript/tsWorker.js application/javascript
upload [90] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/editor/editor.main.nls.js vs/editor/editor.main.nls.js application/javascript
upload [80] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/vs/basic-languages/javascript/javascript.js vs/basic-languages/javascript/javascript.js application/javascript
upload [70] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/static/js/main.8e727556.chunk.js static/js/main.8e727556.chunk.js application/javascript
upload [60] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/index_m.html index_m.html text/html
upload [50] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/own/msg/de.js google-blockly/own/msg/de.js application/javascript
upload [40] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/own/blocks_sendto.js google-blockly/own/blocks_sendto.js application/javascript
upload [30] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/msg/js/it.js google-blockly/msg/js/it.js application/javascript
upload [20] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/handopen.cur google-blockly/media/handopen.cur null
upload [19] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/handdelete.cur google-blockly/media/handdelete.cur null
upload [18] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/handclosed.cur google-blockly/media/handclosed.cur null
upload [17] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/dropdown-arrow.svg google-blockly/media/dropdown-arrow.svg image/svg+xml
upload [16] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/disconnect.wav google-blockly/media/disconnect.wav audio/wav
upload [15] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/disconnect.ogg google-blockly/media/disconnect.ogg audio/ogg
upload [14] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/disconnect.mp3 google-blockly/media/disconnect.mp3 audio/mpeg
upload [13] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/delete.wav google-blockly/media/delete.wav audio/wav
upload [12] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/delete.ogg google-blockly/media/delete.ogg audio/ogg
upload [11] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/delete.mp3 google-blockly/media/delete.mp3 audio/mpeg
upload [10] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/click.wav google-blockly/media/click.wav audio/wav
upload [9] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/click.ogg google-blockly/media/click.ogg audio/ogg
upload [8] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/click.mp3 google-blockly/media/click.mp3 audio/mpeg
upload [7] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/media/1x1.gif google-blockly/media/1x1.gif image/gif
upload [6] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/javascript_compressed.js google-blockly/javascript_compressed.js application/javascript
upload [5] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/blocks_compressed.js google-blockly/blocks_compressed.js application/javascript
upload [4] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/blockly_compressed.js google-blockly/blockly_compressed.js application/javascript
upload [3] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/google-blockly/LICENSE google-blockly/LICENSE null
upload [2] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/favicon.ico favicon.ico image/vnd.microsoft.icon
upload [1] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/asset-manifest.json asset-manifest.json application/json
upload [0] javascript.admin /opt/iobroker/node_modules/iobroker.javascript/admin/adminWords.js adminWords.js application/javascript
Adapter "javascript" updated
process exited with code 0`

**Comment by ticaki** [comment] 2021-09-12 10:07
Zusätzlich zu den oben genannten Problemen, Kennt er setTimeout und clearTimeout nicht mehr. Bin zurück auf .9

**Comment by DutchmanNL** [comment] 2021-09-12 10:26
> Zusätzlich zu den oben genannten Problemen, Kennt er setTimeout und clearTimeout nicht mehr. Bin zurück auf .9

Bitte neues issue dafür sonst blicken wir nicht mehr durch bzw übersehen eventuell was

**Comment by daniel-lo** [comment] 2021-09-12 11:55
Lässt sich bei mir auch nicht updaten .. weder per GUI noch per GIT

**Comment by PeterVoronov** [comment] 2021-09-12 12:12
> Version in io-package is wrong
> 
> https://github.com/ioBroker/ioBroker.javascript/blob/master/io-package.json#L23
Confirmed.
De-facto it is upgraded, but due to wrong version io-package.json ths system still identify it as old one.

**Comment by Apollon77** [comment] 2021-09-12 14:30
fixed by .12

**Closed** 2021-09-12 14:30 UTC
