### ISSUE TITLE
Sendto-Blocks not selectable

### ISSUE THREAD

**Issue by DanRieLa** [ioBroker/ioBroker.javascript#46] opened 2017-10-26 04:44 UTC
Status:
iobroker installed on Raspberry Pi 3 with latest Jessie 
node v6.11.2
iobroker Admin v. 2.0.7
Javascript/Blockly engine v. 3.4.0
Telegram v1.0.8
Email v1.0.2
Browsers tested: Firefox, Chrome, IE10

Issue:
Under "SendTo" only the telegram-block is visible, sometimes it will be be covered by the sidebar.
The block won't be highlighted with a yellow edge when mouse hovers over it, it is not drag&drop-able.

![grafik](https://user-images.githubusercontent.com/33111642/32035315-a266261a-ba18-11e7-8c81-8fce28d80a8a.png)

Behaviour for all other blocks is fine (highlight+drag+drop): 
![grafik](https://user-images.githubusercontent.com/33111642/32035355-ebb84852-ba18-11e7-8ee7-5a129c237966.png)

**Comment by GermanBluefox** [comment] 2017-10-26 09:58
There must be an error in browser console. Please provide it. Thank you.

26 окт. 2017 г. 6:44 пользователь "DanRieLa" <notifications@github.com>
написал:

Status:
iobroker installed on Raspberry Pi 3 with latest Jessie
node v6.11.2
iobroker Admin v. 2.0.7
Javascript/Blockly engine v. 3.4.0
Telegram v1.0.8
Email v1.0.2
Browsers tested: Firefox, Chrome, IE10

Issue:
Under "SendTo" only the telegram-block is visible, sometimes it will be be
covered by the sidebar.
The block won't be highlighted with a yellow edge when mouse hovers over
it, it is not drag&drop-able.

[image: grafik]
<https://user-images.githubusercontent.com/33111642/32035315-a266261a-ba18-11e7-8c81-8fce28d80a8a.png>

Behaviour for all other blocks is fine (highlight+drag+drop):
[image: grafik]
<https://user-images.githubusercontent.com/33111642/32035355-ebb84852-ba18-11e7-8ee7-5a129c237966.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ioBroker/ioBroker.javascript/issues/46>, or mute the
thread

**Comment by DanRieLa** [comment] 2017-10-26 15:41
Hi GermanBlueFox,

thank you for looking into it.
The Console from Firefox says (when trying to use Sento Blocks):
window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung.  ace.js:1:18478
Passwort-Felder sind auf einer unsicheren (http://) Seite vorhanden. Dies ist ein Sicherheitsrisiko, durch das Zugangsdaten gestohlen werden können.[Weitere Informationen]  192.168.172.24:8081
"Default ACL": {"en": "Default ACL", "de": "Default ACL", "ru": "Default ACL"},  translate.js:24:9
"Access control list": {"en": "Access control list", "de": "Access control list", "ru": "Access control list"},  translate.js:24:9
"File rights": {"en": "File rights", "de": "File rights", "ru": "File rights"},  translate.js:24:9
"Default ACL": {"en": "Default ACL", "de": "Default ACL", "ru": "Default ACL"},  translate.js:24:9
"Access control list": {"en": "Access control list", "de": "Access control list", "ru": "Access control list"},  translate.js:24:9
"File rights": {"en": "File rights", "de": "File rights", "ru": "File rights"},  translate.js:24:9
window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung.  ace.js:1:18478
**Detected custom blockly: cloud  tab.js:1744:17
Detected custom blockly: telegram  tab.js:1744:17
TypeError: c is undefined[Weitere Informationen]  blockly_compressed.js:1265:254**

        
Edge says:

2 SCRIPT5007: Unable to get property '1' of undefined or null reference
blockly_compressed.js (1264,253)

 Ignoring non-existent input END_TIME in block time_compare_ex
blockly_compressed.js (1006,110)

 Ignoring non-existent input CUSTOM_TIME in block time_compare_ex
blockly_compressed.js (1006,110)

 Ignoring non-existent input END_TIME in block time_compare
blockly_compressed.js (1006,110)

 Ignoring non-existent input FORMAT in block time_get
blockly_compressed.js (1006,110)

 Ignoring non-existent input LANGUAGE in block time_get
blockly_compressed.js (1006,110)

2 SCRIPT5007: Unable to get property '1' of undefined or null reference
blockly_compressed.js (1264,253)

Hope you might solve it, thanks for your time

**Comment by GermanBluefox** [comment] 2019-02-28 22:01
Still reproducible?

**Comment by BuZZy1337** [comment] 2019-03-01 08:29
That was fixed in the regarding adapters.

It was not a iobroker.javascript issue at all..

**Closed** 2019-03-01 08:31 UTC
Labels: question
