### ISSUE TITLE
[Bug]: And- Block is not working correct if or condition is inside

### ISSUE THREAD

**Issue by BrightM91** [ioBroker/ioBroker.javascript#1572] opened 2024-05-13 15:15 UTC
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

![Screenshot 2024-05-13 170509](https://github.com/ioBroker/ioBroker.javascript/assets/142607162/bd3bdc0d-a986-4fdf-9edd-e225b0930899)
In the shown case, the whole block should only be true if (C1 or C2 ) and C3 are true
I found the case that the whole block is true if C1 is true or (C2 and C3)

when I'm looking at the javascript version of the blockly generated they are connected like C1 || C2 && C3 but I think it should be (C1 || C2) && C3

### Version of nodejs

v18.20.2

### Version of ioBroker js-controller

5.0.19

### Version of adapter

7.8.0

**Comment by klein0r** [comment] 2024-05-13 15:45
> ### Version of adapter
> 7.8.0

That's quite old. Already fixed in the current version

**Closed by klein0r** 2024-05-13 15:45 UTC

**Comment by klein0r** [comment] 2024-05-13 17:17
Duplicate of #1540
