### ISSUE TITLE
4.0: script editor file menu highlighting does not correspond to file being edited

### ISSUE THREAD

**Issue by mclane** [ioBroker/ioBroker.javascript#204] opened 2018-11-29 17:02 UTC
When opening a file for editing (doubleclick) this file does not stay highlighted in the file menu
![iobrokereditor](https://user-images.githubusercontent.com/1165738/49238186-2bfd5480-f400-11e8-81f2-5d2e6639d97e.png)
see screenshot above: I opened the script M_ShutterDaily by double clicking in the file menu, but the file HZ_getETAData stays highlighted

**Comment by GermanBluefox** [comment] 2018-12-04 13:37
Tested with Chrome and FF. Cannot reproduce....
![js](https://user-images.githubusercontent.com/4582016/49445418-2b830600-f7d2-11e8-84a9-971fa648fae4.gif)

**Comment by mclane** [comment] 2018-12-04 17:21
Ok, it works now (magically?). However, I downgraded the javascript adapter back to 3.6.4, but the new editor stayed. How can I get rid of the new editor?

**Comment by AlCalzone** [comment] 2018-12-04 18:46
perform an upload of the adapter in the adapter list and clear your cache

**Comment by AlCalzone** [comment] 2018-12-05 18:56
I can confirm it in 4.0.2

**Comment by AlCalzone** [comment] 2018-12-05 18:59
![ezgif com-crop](https://user-images.githubusercontent.com/17641229/49537099-518ad200-f8c8-11e8-8867-c68821d27679.gif)

**Comment by GermanBluefox** [comment] 2019-02-26 21:35
Must be fixed in 4.1.5

**Comment by AlCalzone** [comment] 2019-02-27 07:12
It works one way now. But selecting a tab does not update the selection on the left.

**Comment by GermanBluefox** [comment] 2019-02-28 22:34
Duplicate to https://github.com/ioBroker/ioBroker.javascript/issues/238#issuecomment-468419359

**Closed by GermanBluefox** 2019-02-28 22:34 UTC
