### ISSUE TITLE
[Bug]: Problem with new Blockly elements (like http POST)... (un-usable)

### ISSUE THREAD

**Issue by Roellen** [ioBroker/ioBroker.javascript#1618] opened 2024-06-25 17:38 UTC
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

Blockly

### The problem

Whenever I add one of the new Blockly-elements like "http (POST)... the Blockly-script does not recognize any changes made in the scripts. 
So the button "save" does never show up.
And actually it even does not save the script at all. 

The script only works again after removing the "http (POST)" blockly element. 

https://www.youtube.com/watch?v=qtATdalX8vc

### Version of nodejs

18.19.0

### Version of ioBroker js-controller

5.0.19

### Version of adapter

8.3.1 
(at first i entered the wrong version number v3.3.0)

**Comment by mcm1957** [comment] 2024-06-25 18:00
Either you should update your java-script adapter or the noted version is incorrect. 3.3.0 is VERY old if correct :-)

**Comment by Roellen** [comment] 2024-06-25 18:12
Ups!
My failt. It‘s 8.3.1

**Comment by klein0r** [comment] 2024-06-25 18:52
Duplicate of #1577

Always use the latest beta for issue reports and search for existing (and maybe closed issues)

**Closed by klein0r** 2024-06-25 18:52 UTC
