### ISSUE TITLE
[Bug]: No PopUp when importing Scripts

### ISSUE THREAD

**Issue by schoenni** [ioBroker/ioBroker.javascript#1679] opened 2024-08-08 08:05 UTC
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

All

### The problem

Whe clicking on import there is now Popup. Tested on Firefox, Chrome and IE.
Tested on v8.7.6

### Version of nodejs

 v20.16.0

### Version of ioBroker js-controller

6.0.9

### Version of adapter

v8.7.6

**Comment by mcm1957** [comment] 2024-08-08 08:50
Please check with 8.7.7 or newer:
https://github.com/ioBroker/ioBroker.javascript#877-2024-08-04

**Comment by klein0r** [comment] 2024-08-08 09:24
Duplicate of #1651 #1669

**Closed by klein0r** 2024-08-08 09:24 UTC
