### ISSUE TITLE
Scripts generate multiple entries in iobroker Log

### ISSUE THREAD

**Issue by mclane** [ioBroker/ioBroker.javascript#366] opened 2019-03-26 08:05 UTC
When opening the Log Tab in ioBroker (see screenshot), scripts seem to generate 3 times the same log entry at the same time. Something similar is also reported in the forum [https://forum.iobroker.net/topic/18915/javascript-adapter-l%C3%A4uft-mehrfach/30](url) When I close the Log tab and reopen it, the events are shown only once; but new events do appear 3 times again. The problem appears also in the Log section of the Script tab.

![Bildschirmfoto vom 2019-03-26 08-52-38](https://user-images.githubusercontent.com/1165738/54980016-efec9180-4fa4-11e9-8a63-337f5ef12d32.png)

My setup: Debian, 3.4 GB RAM, Node.js = 8.15.0, npm = 6.5.0, javascript adapter = 3.6.5 single host. ps -aux | grep io shows only one instance of the javascript adapter as it should.

**Comment by DutchmanNL** [comment] 2019-03-27 15:02
are you sure the iObroker.javascript Proces runs only ones ?
is the behavior the same when you reboot the system ?
How does your script look like ?

**Comment by roe19xx** [comment] 2019-03-28 06:42
I can confirm this. In in previous Javascript Engine Adapters i had the same behaviour sometimes.
I have two instances of Javascript Engine Adapter in use. Affected was only one of them (the other one only showed one entry in log not three).

When i've restarted the affected adapter then it was solved. But someone later (often days ago) it happens again.

Currently i'am using the Javascript Adapter 4.1.12 and do not have this issue anymore.
I will watch this and report if any status change.

Regards
Roland

**Comment by muellra** [comment] 2019-05-06 20:01
I can confirm the problem!

Im using iobroker on an RaspberryPi 3 in a docker container.
It seems that eather the javascript adapter allows more than one subscription per scripts to register like shown in this logmessage:
"javascript.0 script.js.common.<scriptName>: registered 1 subscription and 0 schedules"
Or otherwise there is a problem in the controller.js that allows more than on javascript instances.

On my system when I connect to the docker container via docker exec i can only see one instance running via the ps -ef command!
Is there a problem saving / syncing the subscription in the DB?
Sometimes my modules get an error like: "warn: javascript.0 Reconnection to DB."

Current Versions:
{
  "name": "iobroker.inst",
  "version": "1.1.2",
  "private": true,
  "description": "Automation platform in node.js",
  "dependencies": {
    "iobroker.admin": "^3.6.0",
    "iobroker.alexa2": "^1.1.3",
    "iobroker.cloud": "^2.6.2",
    "iobroker.discovery": "^1.2.4",
    "iobroker.email": "^1.0.4",
    "iobroker.fhem": "^1.1.1",
    "iobroker.javascript": "^4.1.12",
    "iobroker.js-controller": "^1.4.2",
  }
}

**Comment by Apollon77** [comment] 2019-05-06 23:03
ReconnectionToDB is "bad" and can cause some trouble ... also it could force scripts to run twice.
But in fact subscriptions are not synced to any DB.

You get a "Reconnection to DB" error if the "DB connection PING/PONG" that happens every 20s did not proceed. Reasons can be e.g.:
* js.controller process blocked >20s (but then you should see many such error from different adapters)
* adapter process  blocked >20s ... for javascript adapter this means you have bad scripts that block the nodejs "event loop" >20s ... you should consider rewrite such scripts
* Other problems on system level that cause the processes to get not enough CPU time

So before investing deeper: get rid of the Reconnect to DB errors!

**Comment by muellra** [comment] 2019-05-07 19:31
Thanks for clarification!

In my "fhem.0" adapter I had 9534 object to sync between fhem and iobroker.
"info.Info.numberObjectsIOBin = 9534" that was to much for the RaspberryPi...

After reducing the fhem devices that the adapter has to hold in sync the warning "Reconnection to DB" didn't occure anymore today (since yesterday 10pm).

**Comment by Apollon77** [comment] 2019-05-07 23:08
Then try a reboot to really bring system to clean state and monitor if JavaScript is still doing strange things

**Comment by GermanBluefox** [comment] 2019-08-24 21:23
>are you sure the iObroker.javascript Proces runs only ones ?

I still can't see the answer on this question. So I close it.

**Closed by GermanBluefox** 2019-08-24 21:23 UTC
