### ISSUE TITLE
$-selector misses states again

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#380] opened 2019-05-16 06:57 UTC
This is probably unrelated to #109 
https://forum.iobroker.net/post/261822

**Comment by Garfonso** [comment] 2020-04-17 22:23
I managed to reproduce this issue. It is connected with objects not having a native part. (Which still is true for sonoff.*.*.alive and zigbee.*.*.available, at least in my setup).

The issue is fixed in 4.4.3 (and later probably). In 4.1.12 (version in the report) "[applyNativeSelectors](https://github.com/ioBroker/ioBroker.javascript/blob/master/lib/sandbox.js#L637)" is called for every object no matter if there is a nativeSelector or not. "applyNativeSelectors" then returns [false](https://github.com/ioBroker/ioBroker.javascript/blob/master/lib/sandbox.js#L639) for all objects without native part, i.e. filtering them out.

In some later version (and still today) applyNativeSelctors is only called if there is a nativeSelector. [This if is missing in 4.1.12](https://github.com/ioBroker/ioBroker.javascript/blob/master/lib/sandbox.js#L700).
So today it works as expected, even on objects without native part (they will then fail for nativeSelectors ;-)).

So I'd say it is save to assume this issue fixed. Also the original reporter could not reproduce it.

**Closed** 2020-04-17 22:31 UTC
Labels: bug
