### ISSUE TITLE
Blockly detects changes when scrolling through a script

### ISSUE THREAD

**Issue by Kaiman77** [ioBroker/ioBroker.javascript#1425] opened 2023-10-28 10:31 UTC
In the Blockly editor, the tool usually offers to save the script as soon as a change has been performed.
With some former update (not quite sure which one) the behavior changed.

Now the save button offers to save even when one just scrolls through a script - so just moving the view from left to right or scrolling up and down.
It doesn't necessarily happen in all scripts, but the behavior was confirmed by several users in the german iobroker facebook group.

**To Reproduce**  
open a blockly script, scroll up and down, see if save button offers to save

**Expected behavior**  
Save button should only appear if a real change in the script has been made

**Versions:**  
 - Adapter version: 7.1.4, also happens with 7.1.6 (beta)
 - JS-Controller version: 5.0.12
 - Node version: 18.18.2
 - Operating system: Docker image on Synology NAS

**Additional context**

**Comment by bambi-arch** [comment] 2023-11-03 06:27
Hallo,
ich hab das gleiche Problem, ohne eine Änderung kommt der Speicherbutton. Zusätzlich habe ich die Situation, wenn nur ein Skript in Blockly offen ist, wird der Button "Alle Speichern" angezeigt.
Node Version Update 18.17.1
Host 5.0.12 
Javaskript 7.1.4

![image](https://github.com/ioBroker/ioBroker.javascript/assets/104907692/34f05ed4-f6b6-4195-a129-8a929c6cfc85)

**Comment by klein0r** [comment] 2023-12-04 14:51
I'm not able to reproduce that

![Test](https://github.com/ioBroker/ioBroker.javascript/assets/1959049/5bc08a35-8762-4b40-b0a3-4e31d5e48f7f)

**Comment by M1cS0w** [comment] 2023-12-04 23:44
Hallo,

ich habe dasselbe Problem. Ist mir heute erst aufgefallen. Aktuelle Version ist installiert 7.1.6.
Habe auch einmal die vorherige Version installiert: 7.1.4, dasselbe Problem.

Wenn man gespeichert hat, hat man erstmal Ruhe, nach dem Schließen und erneuten Öffnen eines Scripts, ist das Problem erneut vorhanden.

---------------------------------

Hello,

I have the same problem. I only noticed it today. Current version is installed 7.1.6.
I also installed the previous version once: 7.1.4, same problem.

Once you have saved, you have peace of mind, after closing and reopening a script, the problem is there again.

----------


system:
![image](https://github.com/ioBroker/ioBroker.javascript/assets/51213428/b852abf2-800a-441e-8fe3-06d3079756d3)

Hier einmal das Video der Reproduktion:

https://github.com/ioBroker/ioBroker.javascript/assets/51213428/883e34b8-0556-43be-acc6-2a70b119ab9f

**Comment by Kaiman77** [comment] 2023-12-05 07:28
Same here.
And according to the Facebook iobroker group, there seem to be some more people with that problem.
Unfortunately I currently have no really good idea how to make this happen on your machine as well.

https://github.com/ioBroker/ioBroker.javascript/assets/47158634/76135b50-6b5b-4703-8f35-cc60609e35eb

**Comment by Diginix** [comment] 2023-12-05 07:28
I had the same issue and for me it seems to be fixed with v7.2.0.

**Comment by Kaiman77** [comment] 2023-12-05 07:45
ok, v7.2.0 is just on github I assume?

**Comment by Diginix** [comment] 2023-12-05 08:15
Was released yesterday in latest repo.
https://github.com/ioBroker/ioBroker.javascript#720-2023-12-04

**Comment by Kaiman77** [comment] 2023-12-05 08:31
Ah - didn't show up, but a reload helped.
The issue also appears here with v7.2.0 :-(

**Comment by Diginix** [comment] 2023-12-05 09:52
@klein0r Should this be fixed with 7.2.0?

**Comment by klein0r** [comment] 2023-12-05 13:16
@Diginix No, since I wasn't able to reproduce that behaviour on any system (Windows, Mac, different Browsers, ...)

**Comment by Diginix** [comment] 2023-12-05 14:57
Until 7.2.0 (incl. 7.1.6) I had the same issue, but can't reproduce it since update to 7.2.0 on two PC.

**Comment by Kaiman77** [comment] 2023-12-06 08:53
@funchenry : That's not the behavior I can see. My example script aboce doesn't include own objects as triggers but still has that behavior. Restart or not.
But if it helps to recreate the issue on other machines, that would be good.

PS: we should really agree on a language here - German, English, don't care ;-)

**Comment by Diginix** [comment] 2023-12-06 09:02
For me the issues happened in nearly all scripts. No matter what trigger or objects.
After opening an already saved script and just scroll or zoom and the "save" button appears. But with v7.2.0 it doesn't happen so far.

**Comment by klein0r** [comment] 2023-12-06 09:05
> After opening an already saved script and just scroll or zoom and the "save" button appears.

And if you save the script? Appears the save button every time? It's possible that the generated code has changed in the background (with the same Blocks).

**Comment by Diginix** [comment] 2023-12-06 09:06
Yes. after saving again it still happens.

**Comment by Diginix** [comment] 2023-12-06 20:03
Now the issue is back even with v7.2.0 and scripts that were saved some hours ago with this version.
So, the theory with the obsolete parts of code is also wrong.

**Comment by Nogger82** [comment] 2024-01-15 07:01
Ich habe das gleiche Problem. Meist reicht es schon ein Skript zu öffnen, und es wird angeboten zu speichern. Dann muss ich nur rechtsklick "Bausteine aufräumen" klicken und die Option zu speichern ist weg. 
Dabei fällt zusätzlich auf, dass sich Triggerbausteine verschieben (ähnlich wie Einrücken), wenn ich einen anderen Block editiere.
Aktuelle Version: Javascript v7.1.6.
Browser: Firefox

**Comment by klein0r** [comment] 2024-01-29 18:14
Falls das passiert:

1. Script öffnen
2. Zur JavaScript-Ansicht umschalten (falls noch keine Änderungen erkannt wurden)
3. JavaScript kopieren und hier einfügen
4. Scrollen, sodass eine Änderung angezeigt wird
5. Wieder zur JavaScript-Ansicht umschalten
6. JavaScript kopieren und ebenfalls hier einfügen

**Comment by klein0r** [comment] 2024-01-29 19:53
> ok, ich hab mal ein simples genommen :-)

Okay, da hat sich das Script ja wirklich geändert. Sollte aber nur genau 1x passieren. Also wenn das einmal gespeichert wurde, sollte danach keine Änderung mehr erkannt werden. Das war ja mein Hinweis [oben](https://github.com/ioBroker/ioBroker.javascript/issues/1425#issuecomment-1915442175).

**Comment by Diginix** [comment] 2024-01-29 20:07
vorher:  
```
on({ id: '0_userdata.0.Alexa.Onkyo.Input_TV' /* Onkyo.Input_TV */, change: 'any', ack: false }, async (obj) => {
  let value = obj.state.val;
  let oldValue = obj.oldState.val;
  if ((obj.state ? obj.state.val : '')) {
    // Onkyo Input TV
    if (getState('onkyo.0.Zone1.Power').val) {
      setStateDelayed('onkyo.0.Zone1.Volume' /* Volume */, 40, 1000, false);
      setStateDelayed('samsung.0.Volume.Mute Toggle' /* Volume.Mute Toggle */, true, 2000, false);
    } else {
      setStateDelayed('onkyo.0.Zone1.Volume' /* Volume */, 40, 2000, false);
      setStateDelayed('samsung.0.Volume.Mute Toggle' /* Volume.Mute Toggle */, true, 5000, false);
    }
    setState('onkyo.0.Zone1.InputSelect' /* Input Select */, '23');
    console.log('*** Onkyo Input TV & TV ext. Lautsprecher');
  } else if (getState('onkyo.0.Zone1.Power').val == true) {
    setState('samsung.0.Volume.Mute Toggle' /* Volume.Mute Toggle */, false);
    // Onkyo Input Net
    setState('onkyo.0.Zone1.InputSelect' /* Input Select */, '2B');
    console.log('*** Onkyo Input Net & TV int. Lautsprecher');
  }
});
```

nachher:  
```
on({ id: '0_userdata.0.Alexa.Onkyo.Input_TV' /* Onkyo.Input_TV */, change: 'any' , ack: false }, async (obj) => {
  let value = obj.state.val;
  let oldValue = obj.oldState.val;
  if ((obj.state ? obj.state.val : "")) {
    // Onkyo Input TV
    if (getState('onkyo.0.Zone1.Power').val) {
      setStateDelayed('onkyo.0.Zone1.Volume' /* Volume */, 40, 1000, false);
      setStateDelayed('samsung.0.Volume.Mute Toggle' /* Volume.Mute Toggle */, true, 2000, false);
    } else {
      setStateDelayed('onkyo.0.Zone1.Volume' /* Volume */, 40, 2000, false);
      setStateDelayed('samsung.0.Volume.Mute Toggle' /* Volume.Mute Toggle */, true, 5000, false);
    }
    setState('onkyo.0.Zone1.InputSelect' /* Input Select */, '23');
    console.log('*** Onkyo Input TV & TV ext. Lautsprecher');
  } else if (getState('onkyo.0.Zone1.Power').val == true) {
    setState('samsung.0.Volume.Mute Toggle' /* Volume.Mute Toggle */, false);
    // Onkyo Input Net
    setState('onkyo.0.Zone1.InputSelect' /* Input Select */, '2B');
    console.log('*** Onkyo Input Net & TV int. Lautsprecher');
  }
});
```

**Comment by klein0r** [comment] 2024-02-20 09:06
@Diginix Auch da hat sich Code geändert

> if ((obj.state ? obj.state.val : "")) {
> if ((obj.state ? obj.state.val : '')) {

Ich mach hier mal zu, weil es es immer an Code-Optimierungen liegt und daher nur 1x vorkommen sollte.

**Closed by klein0r** 2024-02-20 09:06 UTC
Labels: bug, Blockly

**Comment by Diginix** [comment] 2024-02-20 09:16
> @Diginix Auch da hat sich Code geändert
> Ich mach hier mal zu, weil es es immer an Code-Optimierungen liegt und daher nur 1x vorkommen sollte.

Kann ich so nicht bestätigen. Selbst Blocklys, an denen ich mehrfach am Tag mit der selben JS Adapter Ver. arbeite, zeigen dieses Verhalten. Ich speichere, mache was anderes, gehe zu Blockly und scrolle darin und erhalte den Speichern Button. Manchmal verunsichert einen das, weil man nicht weiß ob man schon echte Änderungen gemacht hat oder es nur wieder der Bug ist.
Aber wenn es nicht lösbar ist, dann muss ich einfach weiter damit leben.

**Comment by klein0r** [comment] 2024-02-20 09:18
> Aber wenn es nicht lösbar ist, dann muss ich einfach weiter damit leben.

Ist es bestimmt, nur hat sich bisher hier in jedem Beispiel etwas geändert und ich kann das Verhalten nicht reproduzieren.

**Comment by Diginix** [comment] 2024-02-20 09:29
In dem von mir beschriebenem Fall ändert sich sicher auch das js, aber eben innerhalb einer Session und derselben Adapterver.
Warum der Adapter das macht, kann ich nicht sagen. Lass es zu bis jemand weitere Erkenntnisse liefert.

**Comment by klein0r** [comment] 2024-02-20 09:50
> In dem von mir beschriebenem Fall ändert sich sicher auch das js

Jedes Mal? Das sollte ja nur 1x passieren und dann ist gut.

**Comment by Kaiman77** [comment] 2024-02-20 09:53
Bei mir wars so, dass es einmal vorkam. 
Dann bin ich alle Skripte durchgegangen, hab sie bewegt und dann neu gespeichert.
Inzwischen tritt das aber bei allen möglichen Skripten wieder auf - auch jetzt nur einmal bis zum Speichern.

Es kann natürlich sein, dass da ein JS Adapter Update ggf. nochmal die Codegenerierung aus Blockly geändert hat.

**Comment by Diginix** [comment] 2024-02-20 09:53
Das ist ja das nervige an dem Bug. Wenn es nur Codeänderungen zw. den JS Adapter Versionen wären, könnte man es plausibel argumentieren. Aber es passiert ja auch mit Skripten die man innerhalb einer Version bearbeitet. Die Woche hatte ich ein Blockly, welches den Effekt immer wieder mal im Laufe des Tages zeigte.

**Comment by klein0r** [comment] 2024-02-20 10:00
> Es kann natürlich sein, dass da ein JS Adapter Update ggf. nochmal die Codegenerierung aus Blockly geändert hat.

Genau, wobei ich mit den Optimierungen und Anpassungen der älteren Blöcken eigentlich durch bin.

**Comment by Diginix** [comment] 2024-02-27 20:05
Heute habe ich mal wieder ein Skript welches nach Änderungen und Speichern nach dem Scrollen direkt wieder den Speichern Button aktiviert.
Geändert hat sich nur die Reihenfolge der Variablen Deklaration
gespeichertes JS:
`var logging, ts_begin, ts_end, days, unit, ts_format, to, subject, text, att1, att2, att3, att4, att5, att6, hourly, cam1command_snap, cam2command_snap, garage_alarm_triggered, cam_on_count, cam1ping, cam_off_count, cam2ping, alarm_status_check, result, cam1img1, cam2img1, cam_garage_filename, check_IR_off_Dach, timeout_eingang_pic2, timeout_wozi_pic2, cam_off_triggered, alarm_on_time, cam1img2, garage_alarm_triggered_reset2, check_IR_on_Dach, cam_on_triggered, cam2img2, garage_alarm_triggered_reset, timeout_eingang_pic3, timeout_wozi_pic3, cam1img3, reset_cam_on_triggered, cam2img3, reset_cam_off_triggered, timeout_eingang_pic4, timeout_wozi_pic4, cam1pos, cam1img4, cam1led, cam2pos, timeout_cam_on, camOffAlarmTime, cam2img4, cam2led, timeout_eingang_pic5, timeout_wozi_pic5, check_cam1_on, camOnAlarmTime, timeout_cam_off_check_img, cam1img5, check_cam1_on2, timeout_cam_off, cam2img5, timeout_eingang_pic6, timeout_cam_on_email, timeout_cam_off_email, timeout_wozi_pic6, cam1img6, telegram_sent, cam2img6, telegram_sent2, check_cam1_off, timeout_eingang_alarm_email, timeout_cam_on_telegram, timeout_cam_off_telegram, check_cam2_off, timeout_wozi_alarm_email;`

JS nach dem Scrollen/Zoomen:
`var logging, ts_begin, ts_end, days, unit, ts_format, to, subject, text, att1, att2, att3, att4, att5, att6, hourly, cam1command_snap, cam2command_snap, garage_alarm_triggered, cam_on_count, cam1ping, cam_off_count, cam2ping, alarm_status_check, result, cam1img1, cam2img1, cam_garage_filename, check_IR_off_Dach, timeout_eingang_pic2, timeout_wozi_pic2, cam_off_triggered, alarm_on_time, cam1img2, garage_alarm_triggered_reset2, check_IR_on_Dach, cam_on_triggered, cam2img2, garage_alarm_triggered_reset, timeout_eingang_pic3, timeout_wozi_pic3, cam1img3, reset_cam_on_triggered, cam2img3, reset_cam_off_triggered, timeout_eingang_pic4, timeout_wozi_pic4, cam1pos, cam1img4, cam1led, cam2pos, timeout_cam_on, camOffAlarmTime, cam2img4, cam2led, timeout_eingang_pic5, timeout_wozi_pic5, check_cam1_on, camOnAlarmTime, timeout_cam_off_check_img, cam1img5, check_cam1_on2, timeout_cam_off, cam2img5, timeout_eingang_pic6, timeout_cam_on_email, timeout_cam_off_email, timeout_wozi_pic6, cam1img6, telegram_sent, cam2img6, check_cam1_off, telegram_sent2, timeout_eingang_alarm_email, timeout_cam_on_telegram, check_cam2_off, timeout_cam_off_telegram, timeout_wozi_alarm_email;`

**Comment by klein0r** [comment] 2024-02-28 08:50
@Diginix Ja, es kann gut sein, dass die neuere Blockly-Version in den aktuellen Adapter-Versionen einfach die Variablen anders sortiert.

**Comment by Diginix** [comment] 2024-02-28 08:52
Dieses Blockly wurde aber zuvor schon x mal mit derselben JS Adapter Ver. bearbeitet. Die Reihenfolge ändert sich als "willkürlich" und triggert somit den Speichern Button.

**Comment by klein0r** [comment] 2024-02-28 09:04
Dann müsste man den Fehler im Blockly-Core suchen.

**Comment by bambi-arch** [comment] 2024-03-09 14:50
Hallo zusammen, 
ich hatte das Problem auch noch in der Version v7.8.0.
Ich hab nun alle Skripte einmal geöffnet und gespeichert. 
Nach dem Neustart des Adapter kommt bei mir nun nicht mehr beim Öffnen der Speicherbutton.
Erst wenn ich wieder Änderungen gemacht habe, wie gewollt. Auch die RAM-Auslastung (warum auch immer) ist um 40 MB runter! Alles wieder Super!!!

**Comment by klein0r** [comment] 2024-03-11 07:57
> Nach dem Neustart des Adapter

Das sollte keinen Unterschied machen, weil das alles komplett im Frontend passiert und damit die laufende Instanz nicht zu tun hat. Es wird ja nur vom Browser das Objekt geladen, das Blockly aufgebaut und danach wieder in das Objekt gespeichert.
