### ISSUE TITLE
Date and time Block (between) does not work sustainable

### ISSUE THREAD

**Issue by unstressable** [ioBroker/ioBroker.javascript#1456] opened 2023-12-02 08:16 UTC
**Describe the bug**  
The bug at copying this block is known since months:
<img width="596" alt="image" src="https://github.com/ioBroker/ioBroker.javascript/assets/50423935/e6201501-a184-4232-a609-a83284120a0f">

But now, at latest version8 7.1.6 there is another Problem:

This block does not work everytime!
Seems the block has an defect.

Workaround:
When the problem of disfunction appears, it will work, when you put a new block there with exactly the same functions and delete the old one.

I saw, that the bug above dissapears by hiding (or showing) the menu bar on the left (tree structure of scripts).

I assume that the block will stop working then. The hour "18:00" as in the screenshot disapears, but its still in the background and affects the funktionality.

Hope I made it clear, otherwise I'll be here for further questions.

**Comment by klein0r** [comment] 2023-12-02 13:18
Duplicate of #1404

**Closed by klein0r** 2023-12-02 13:18 UTC

**Comment by unstressable** [comment] 2023-12-02 15:56
> Duplicate of #1404

Its not exactly the same.
The „new“ Problem is much more relevant and problematic.

**Comment by klein0r** [comment] 2023-12-02 18:21
> but its still in the background and affects the funktionality.

Please share the generated code of that block.

**Comment by unstressable** [comment] 2023-12-02 20:14
> > but its still in the background and affects the funktionality.
> 
> Please share the generated code of that block.

I deleted the Block, and made it new, but trust me, there's a Difference in the latest updates.

we should pursue this very closely.

**Comment by unstressable** [comment] 2023-12-07 19:58
actually I can't because I renewed all my Scripts running with this block since the made problems after last update.

If there's one more, I'll share.
