### ISSUE TITLE
use --omit=dev

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.javascript#1075] opened 2022-07-15 05:03 UTC
New version 5,8.9 gives this error in the logfile:

<html><body>

javascript.0 | 2022-07-15 06:56:45.132 | error | WARN config production Use `--omit=dev` instead.
-- | -- | -- | --
javascript.0 | 2022-07-15 06:56:45.130 | error | npm

</body>
</html>

**Comment by Apollon77** [comment] 2022-07-15 06:40
This seems to be nopm changes in general... I also have many such logs since update to a latest npm 8

**Comment by daniel-lo** [comment] 2022-07-15 06:49
is there some magic to get rid of this?

**Comment by Apollon77** [comment] 2022-07-15 06:53
not looked into it so far

**Comment by daniel-lo** [comment] 2022-07-15 06:54
take your time :-)

**Comment by klein0r** [comment] 2022-07-15 07:06
Duplicate of #1071 ?

**Comment by daniel-lo** [comment] 2022-07-15 07:08
@klein0r 

Don't think so .. just happens to appear in that log but is not related to the topic

**Closed** 2022-10-24 15:26 UTC
Labels: fixed
