### ISSUE TITLE
[Bug]: httpPost Errors in Log

### ISSUE THREAD

**Issue by arniworx** [ioBroker/ioBroker.javascript#1716] opened 2024-09-10 07:23 UTC
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Script type

JavaScript

### The problem

if an error occurs in httpPost, the internal function always generates a log entry.
all other log messages from httpPost depend on "sandbox.verbose"
maybe it's possible to make errors also depend on that variable.

### Version of nodejs

v20.17.0

### Version of ioBroker js-controller

5.0.19

### Version of adapter

v8.8.3

**Comment by klein0r** [comment] 2024-09-10 07:26
Duplicate of #1599

**Closed by klein0r** 2024-09-10 07:26 UTC
