### ISSUE TITLE
jsonata finds no keys with dash (and some other special characters)

### ISSUE THREAD

**Issue by l4rs** [ioBroker/ioBroker.javascript#972] opened 2022-03-01 21:17 UTC
I have set up a Blockly that should inform about possible adapter updates. It was noticed that for adapters with a "-" in the name, the version number cannot be extracted from the JSON.
If you remove the hyphen from the name, the jsonata works as expected and returns the appropriate version numbers. The same problem also occurs with some other special characters - I assume the input is not/not properly escaped...

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/1215848/156248256-64734d62-8c2c-4f70-bc4c-ae8bd21bb35d.png)
![image](https://user-images.githubusercontent.com/1215848/156249833-8c9e42fb-dd65-4182-b8f1-680506853d31.png)

**Versions:** 
- Adapter version: javascript: v5.2.21
 - JS-Controller version: v3.3.2
 - Node version: v12.22.10

[blockly.txt](https://github.com/ioBroker/ioBroker.javascript/files/8164800/blockly.txt)

**Comment by l4rs** [comment] 2022-03-01 21:21
Hey, @klein0r, sorry, but I have no experience with debugging ioBroker javascripts at all, otherwise I might have found the error myself.
I hope you have all the info you need?

**Comment by klein0r** [comment] 2022-03-01 21:33
I think that behavior is correct. The hyphen is interpreted as a subtraction: https://docs.jsonata.org/expressions

**Comment by klein0r** [comment] 2022-03-01 22:05
Okay, I've tested this.

## Problem

Just a simple example Script:

<img width="747" alt="Screenshot 2022-03-01 at 22 57 19" src="https://user-images.githubusercontent.com/1959049/156255764-0c084a58-eeee-4130-bde0-9eb7ae981737.png">

It generates the following code:

```javascript
var myObj;

myObj = (function () { try {return JSON.parse('{"hmrega": {"installedVersion": "1.0.0", "availableVersion": "2.0.0"}}');} catch(e) {return {};}})();
console.log(jsonataExpression(myObj,'hmrega.installedVersion'));
```

**Output: 1.0.0**

Everything works fine. Now I've added the hyphen:

<img width="739" alt="Screenshot 2022-03-01 at 22 59 01" src="https://user-images.githubusercontent.com/1959049/156255959-d996aeb6-eccd-44b9-accc-84cbcda6a3e6.png">

```javascript
var myObj;

myObj = (function () { try {return JSON.parse('{"hm-rega": {"installedVersion": "1.0.0", "availableVersion": "2.0.0"}}');} catch(e) {return {};}})();
console.log(jsonataExpression(myObj,'hm-rega.installedVersion'));
```

**Output: undefined**

## Solution

The hyphen is interpreted as a minus / subtraction. So we have to wrap it in ``"`` to avoid that:

<img width="766" alt="Screenshot 2022-03-01 at 23 04 43" src="https://user-images.githubusercontent.com/1959049/156256663-b92d0368-b1fc-4e32-ab50-2d6291bb61d2.png">

```javascript
var myObj;

myObj = (function () { try {return JSON.parse('{"hm-rega": {"installedVersion": "1.0.0", "availableVersion": "2.0.0"}}');} catch(e) {return {};}})();
console.log(jsonataExpression(myObj,'"hm-rega".installedVersion'));
```

**Output: 1.0.0**

## Solution 2

<img width="765" alt="Screenshot 2022-03-01 at 23 01 04" src="https://user-images.githubusercontent.com/1959049/156256525-1014dfb4-9e8c-47fd-b91e-23cb53940d95.png">

```javascript
var myObj;

myObj = (function () { try {return JSON.parse('{"hm-rega": {"installedVersion": "1.0.0", "availableVersion": "2.0.0"}}');} catch(e) {return {};}})();
console.log(jsonataExpression(myObj,'*["hm-rega"].installedVersion'));
```

**Output: 1.0.0**

**Comment by klein0r** [comment] 2022-03-01 22:09
The reason is, that you can do something like this:

<img width="633" alt="Screenshot 2022-03-01 at 23 07 40" src="https://user-images.githubusercontent.com/1959049/156257028-7bb77fda-1e39-4406-a9a6-8c08d3881f2f.png">

```javascript
var myObj;

myObj = (function () { try {return JSON.parse('{"one": 10, "two": 2}');} catch(e) {return {};}})();
console.log(jsonataExpression(myObj,'one-two'));
```

As you see, there is no key named "one-two". It starts a calculation.

**Output: 8**

So: No issue, the issue is in the script.
Please close this issue 👍

**Closed** 2022-03-03 10:45 UTC

**Comment by klein0r** [comment] 2022-03-03 13:45
Feel free to write some documentation 👍
