### ISSUE TITLE
Using imports in TypeScript global scripts

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.javascript#694] opened 2020-10-31 18:12 UTC
**Describe the bug**  
As soon as a global TypeScript script uses `import ...` all scripts break.

**To Reproduce**  
1. Create a global TypeScript script
2. Use an external library that requires an import
3. Create a non-global script
4. Compiler error: types defined in the global script cannot be found

**Expected behavior**  
I can implement and use classes that require `import`s globally.

**Screenshots & Logfiles**  

```
2020-10-31 16:45:06.248 - info: javascript.0 (23880) script.js.global.Stream: compiling TypeScript source...
2020-10-31 16:45:15.487 - info: javascript.0 (23880) script.js.global.Stream: TypeScript compilation successful
2020-10-31 16:45:31.399 - error: javascript.0 (23880) script.js.Automation.Heating_Period: TypeScript compilation failed:
Notifier.notify('Heating period ended');
^
ERROR: Cannot find name 'Notifier'.
Notifier.notify('Heating period started');
^
ERROR: Cannot find name 'Notifier'.
```

The error message above relates to [my `Notifier` global script](https://github.com/agross/iobroker-scripts/blob/master/0/global/Notifier.ts) (which does not use `import`s). It no longer works, although I only added `Streams.ts` (see below).

**Versions:**  
 - Adapter version: latest
 - JS-Controller version: 3.1.5
 - Node version: 12
 - Operating system: docker

**Additional context**  

I'd like to use this piece of code globally. It makes it easier to create an Rx Observable from an ioBroker state.

```ts
import { concat, EMPTY, Observable, of } from 'rxjs';
import {
  distinctUntilChanged,
  share,
} from 'rxjs/operators';

class Stream<T> {
  private state: string;
  private _stream: Observable<T>;

  constructor(state: string) {
    this.state = state;

    this._stream = concat(this.initialValue, this.changes).pipe(
      distinctUntilChanged(),
    );
  }

  public get stream(): Observable<T> {
    return this._stream;
  }

  private get initialValue(): Observable<T> {
    const current = getState(this.state);
    if (current.notExist) {
      return EMPTY;
    }

    return of(current.val);
  }

  private get changes(): Observable<T> {
    return new Observable<T>(observer => {
      on({ id: this.state, ack: true }, event => {
        observer.next(event.state.val);
      });
    }).pipe(share());
  }
}
```

**Comment by agross** [comment] 2020-10-31 18:13
@AlCalzone Perhaps you have some ideas about what could possibly be wrong here?

**Comment by AlCalzone** [comment] 2020-10-31 20:03
I'll check it out, thanks for the report. Could you show me the raw object definition of the global script object (script.js.global.<scriptname>) please?

**Comment by agross** [comment] 2020-10-31 20:08
Notifier:

```json
{
  "common": {
    "name": "Notifier",
    "expert": true,
    "engineType": "TypeScript/ts",
    "engine": "system.adapter.javascript.0",
    "source": "class Notifier {\n  public static notify(message: string): void {\n    sendTo('pushbullet', {\n      message: message,\n      title: 'ioBroker',\n      type: 'note',\n    });\n  }\n}\n",
    "debug": false,
    "verbose": false,
    "enabled": true,
    "sourceHash": "6a135fe84d6066806bcd71f9b967731b",
    "compiled": "var Notifier = /** @class */ (function () {\r\n    function Notifier() {\r\n    }\r\n    Notifier.notify = function (message) {\r\n        sendTo('pushbullet', {\r\n            message: message,\r\n            title: 'ioBroker',\r\n            type: 'note',\r\n        });\r\n    };\r\n    return Notifier;\r\n}());\r\n",
    "declarations": "declare class Notifier {\r\n    static notify(message: string): void;\r\n}\r\n"
  },
  "type": "script",
  "from": "system.adapter.javascript.0",
  "user": "system.user.agross",
  "ts": 1604167283783,
  "_id": "script.js.global.Notifier",
  "acl": {
    "object": 1636,
    "owner": "system.user.agross",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}
```

Stream:

```json
{
  "common": {
    "name": "Stream",
    "expert": true,
    "engineType": "TypeScript/ts",
    "engine": "system.adapter.javascript.0",
    "source": "import { concat, EMPTY, Observable, of } from 'rxjs';\nimport {\n  distinctUntilChanged,\n  share,\n} from 'rxjs/operators';\n\nclass Stream<T> {\n  private state: string;\n  private _stream: Observable<T>;\n\n  constructor(state: string) {\n    this.state = state;\n\n    this._stream = concat(this.initialValue, this.changes).pipe(\n      distinctUntilChanged(),\n    );\n  }\n\n  public get stream(): Observable<T> {\n    return this._stream;\n  }\n\n  private get initialValue(): Observable<T> {\n    const current = getState(this.state);\n    if (current.notExist) {\n      return EMPTY;\n    }\n\n    return of(current.val);\n  }\n\n  private get changes(): Observable<T> {\n    return new Observable<T>(observer => {\n      on({ id: this.state, ack: true }, event => {\n        observer.next(event.state.val);\n      });\n    }).pipe(share());\n  }\n}",
    "debug": false,
    "verbose": false,
    "enabled": true,
    "sourceHash": "bcf25cbd76a5f106b66e182fa0c0978c",
    "compiled": "\"use strict\";\r\nObject.defineProperty(exports, \"__esModule\", { value: true });\r\nvar rxjs_1 = require(\"rxjs\");\r\nvar operators_1 = require(\"rxjs/operators\");\r\nvar Stream = /** @class */ (function () {\r\n    function Stream(state) {\r\n        this.state = state;\r\n        this._stream = rxjs_1.concat(this.initialValue, this.changes).pipe(operators_1.distinctUntilChanged());\r\n    }\r\n    Object.defineProperty(Stream.prototype, \"stream\", {\r\n        get: function () {\r\n            return this._stream;\r\n        },\r\n        enumerable: false,\r\n        configurable: true\r\n    });\r\n    Object.defineProperty(Stream.prototype, \"initialValue\", {\r\n        get: function () {\r\n            var current = getState(this.state);\r\n            if (current.notExist) {\r\n                return rxjs_1.EMPTY;\r\n            }\r\n            return rxjs_1.of(current.val);\r\n        },\r\n        enumerable: false,\r\n        configurable: true\r\n    });\r\n    Object.defineProperty(Stream.prototype, \"changes\", {\r\n        get: function () {\r\n            var _this = this;\r\n            return new rxjs_1.Observable(function (observer) {\r\n                on({ id: _this.state, ack: true }, function (event) {\r\n                    observer.next(event.state.val);\r\n                });\r\n            }).pipe(operators_1.share());\r\n        },\r\n        enumerable: false,\r\n        configurable: true\r\n    });\r\n    return Stream;\r\n}());\r\n",
    "declarations": "export {};\r\n"
  },
  "type": "script",
  "from": "system.adapter.javascript.0",
  "user": "system.user.admin",
  "ts": 1604174844993,
  "_id": "script.js.global.Stream",
  "acl": {
    "object": 1636,
    "owner": "system.user.agross",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}
```

**Comment by AlCalzone** [comment] 2020-10-31 20:50
I can reproduce, but I'm not sure yet what is happening.

**Comment by AlCalzone** [comment] 2020-10-31 21:10
The import causes TS to treat the global script containing it as a module, so the generated declaration only contains `export {}`. In addition, the global declarations are concatenated, which also means that the concatenated declaration is now a module. This means that `declare class` from the `Notifier` script is no longer visible for the consuming script.

I'll play around a bit with some transforms, but I fear that this makes it impossible to pre-compile global scripts.

**Comment by agross** [comment] 2020-10-31 21:31
Thank you for looking into this!

As an alternative, perhaps one could scrap that global magic for TypeScript and instead use project-based builds? See my script repo where you can `npm run build`. At least to me that would seem like a cleaner, even supported, method of reusing scripts.

**Comment by AlCalzone** [comment] 2020-11-01 14:19
The problem is that as soon as TypeScript finds an `import` or `export` statement, it treats the file as a module. For "normal" scripts we want this (reusing variable names), for global scripts we don't. But there's no good way to turn that off.
I've wanted to use **script modules** for the script VMs for a while now (which would solve all my headaches related to global scripts), but the feature has been postponed over and over.

As for your problem, all I can propose for now is a suboptimal workaround:

1. Convert all value imports into `require` statements:
```ts
// before:
import { concat, EMPTY, Observable, of } from 'rxjs';
// after:
const { concat, EMPTY, Observable, of } = require('rxjs') as typeof import("rxjs");
```
This has the downside that you have to specify the module type too. 

2. Convert all type imports into `type` declarations. This also applies if you need any of the above imports in a type position:
```ts
type Observable<T> = import('rxjs').Observable<T>;
```
Again there's a downside - at least I couldn't get it to work correctly. `Observable<T>` in a type position will be `any`.

---

I'll investigate a different idea for the compilation process, which is similar to the magic we now do for top-level-await:
* add export statements to everything at the root level, which causes them to be included in the generated declarations
* wrap the generated declarations in `declare global`

**Comment by AlCalzone** [comment] 2020-11-03 19:22
@agross please test the version in PR #701

**Comment by agross** [comment] 2020-11-04 08:45
Unfortunately, I still see the same errors:

```
2020-11-04 09:43:11.683 - error: javascript.0 (20585) script.js.Automation.Heating_Period: TypeScript compilation failed:
--
Notifier.notify('Heating period ended');
^
ERROR: Cannot find name 'Notifier'.
Notifier.notify('Heating period started');
^
ERROR: Cannot find name 'Notifier'.
```

**Comment by agross** [comment] 2020-11-04 08:48
Scratch that, installing the #701 did not work:

```
2020-11-04 09:46:28.262  - info: host.iobroker iobroker NPM version: 6.14.6
2020-11-04 09:46:28.265  - info: host.iobroker iobroker npm install https://github.com/ioBroker/ioBroker.javascript/pull/701/tarball/4fa4c0eaf01bb39cfc301c9d93313a5b73ef6ac1 --loglevel error --prefix "/opt/iobroker" (System call)
2020-11-04 09:46:40.884  - info: host.iobroker iobroker npm
2020-11-04 09:46:40.886  - info: host.iobroker iobroker  ERR! code E404
2020-11-04 09:46:40.890  - info: host.iobroker iobroker npm
2020-11-04 09:46:40.893  - info: host.iobroker iobroker  ERR! 404 Not Found - GET https://github.com/ioBroker/ioBroker.javascript/pull/701/tarball/4fa4c0eaf01bb39cfc301c9d93313a5b73ef6ac1npm ERR! 404 npm ERR! 404  'https://github.com/ioBroker/ioBroker.javascript/pull/701/tarball/4fa4c0eaf01bb39cfc301c9d93313a5b73ef6ac1' is not in the npm registry.npm ERR! 404 Your package name is not valid, because npm ERR! 404  1. name can only contain URL-friendly charactersnpm ERR! 404  2. name can no longer contain capital lettersnpm ERR! 404 npm ERR! 404 Note that you can also install from anpm ERR! 404 tarball, folder, http url, or git URL.
```

**Comment by agross** [comment] 2020-11-04 09:08
Installation worked with https://github.com/ioBroker/ioBroker.javascript/tarball/582aa9e4405fdba17ff2d6ed2c4e546faa6c7a80.

New errors popped up (I have several scripts declaring `scene` and `sensor`, but no global scripts declare them):

```
2020-11-04 10:01:17.445 - error: javascript.0 (21990) script.js.Lights.Utility_Room_Lights: TypeScript compilation failed:
--
const sensor = 'zigbee.1.00158d00045c1216.opened';
^
ERROR: Cannot redeclare block-scoped variable 'sensor'.
const scene = 'scene.0.Utility Room.Entered';
^
ERROR: Cannot redeclare block-scoped variable 'scene'.
```

And:

```
2020-11-04 10:05:35.233 - error: javascript.0 (22345) script.js.global.Object_Creator: TypeScript compilation failed:
--
export type ObjectDefinition = iobJS.Object & {
^
ERROR: Namespace 'iobJS' has no exported member 'Object'.
private static definition(definition: ObjectDefinition): iobJS.Object {
^
ERROR: Namespace 'iobJS' has no exported member 'Object'.
```

**Comment by agross** [comment] 2020-11-04 09:10
The second error shows up regardless of my global script defining `Stream`.

**Comment by AlCalzone** [comment] 2020-11-04 09:29
> Installation worked with https://github.com/ioBroker/ioBroker.javascript/tarball/582aa9e4405fdba17ff2d6ed2c4e546faa6c7a80.

Pro tip: next time install `ioBroker/ioBroker.javascript#branch-name`, which is `ioBroker/ioBroker.javascript#global-script-import-fix` in this case :)

> ERROR: Cannot redeclare block-scoped variable 'sensor'.

That error error likely means that the transformation of normal scripts is now doing something it shouldn't. I need to look at the test cases, but this **should** already be tested.

> ERROR: Namespace 'iobJS' has no exported member 'Object'.

Heh, now the global declarations interfere with the predefined ones :(

**Comment by AlCalzone** [comment] 2020-11-04 10:46
I've pushed a fix for the first error, however I cannot reproduce your second error in a test case.
If that is still happening, could you please provide me with some scripts that cause the error? And please don't forget to edit and save all the affected scripts first.

**Comment by agross** [comment] 2020-11-04 10:48
> could you please provide me with some scripts that cause the error

https://github.com/agross/iobroker-scripts/blob/master/0/global/Object_Creator.ts

> And please don't forget to edit and save all the affected scripts first.

What do you mean? After upgrading the adapter?

**Comment by AlCalzone** [comment] 2020-11-04 10:52
> What do you mean? After upgrading the adapter?

Yes. Compiled TypeScripts are now cached on the script objects and aren't recompiled unless their source code or the used definitions change.
Because the import fix (and some other fixes) require a new compilation, you must force the new compilation by changing the source code (e.g. by adding a space or an empty line) and saving the script.

**Comment by agross** [comment] 2020-11-04 10:54
Interesting. What I did was to add (and start) a new global script. As far as I understood this will also cause a recompilation of everything?

**Comment by AlCalzone** [comment] 2020-11-04 10:59
It might not recompile the other global scripts because of their (somewhat weird) dependency order.

**Comment by agross** [comment] 2020-11-04 11:00
> aren't recompiled unless their source code or the used definitions change

I see some cache invalidation bugs coming your way. E.g.:

1. User compiles script in version 4.9.5 of the adapter.
1. The script remains unchanged and thus is cached.
1. The user updates to 4.9.6 which introduces a bug.
1. The user updates to 4.9.7 which still contains the bug.
1. The user touches the script (adding a space as suggested) which forces a recompile.
1. The user sees the script break and blames 4.9.7, although 4.9.6. is the culprit.

I suggest using not only the script itself as a cache key but all its dependencies (perhaps as a SHA).

**Comment by AlCalzone** [comment] 2020-11-04 11:06
The global scripts a script depends on are also included in the source hash by hashing the generated declarations. So if one global script changes, the depending global scripts will all be recompiled, which causes the non-global scripts to also be recompiled.

Adding a new global script (which should be at the end of the dependency chain) will not cause the other global scripts to be recompiled though.

It is probably a good idea to include the script adapter version in the hash computation aswell. This will have the downside that all TypeScripts will be recompiled after an update, but avoids not getting transformation bugs fixed by updating.

**Comment by AlCalzone** [comment] 2020-11-04 11:24
> > could you please provide me with some scripts that cause the error
> 
> https://github.com/agross/iobroker-scripts/blob/master/0/global/Object_Creator.ts

Ok this problem has to do with the transformations I need to do in order to fix the other issues. Luckily it can be fixed pretty simple:
Since global scripts are now forced to be treated as modules, you need to do one additional step to achieve namespace merging for the global namespace `iobJS`:
```diff
+ declare global {
    namespace iobJS {
        export type AliasCommon = {
            alias?:
            | string
            | {
                read?: string;
                write?: string;
                id: string | { read?: string; write?: string };
                };
        };

        export type CustomCommon = {
            custom?: {};
        };
    }
+ }
```
This will cause the editor to complain (`Augmentations for the global scope can only be directly nested in external modules or ambient module declarations.(2669)`), but you can fix that by importing something or adding an empty `export {};` statement somewhere. The code transformation will do that anyways before compilation, so it also won't break anything.

**Comment by AlCalzone** [comment] 2020-11-04 11:26
Let me know if that solves your remaining problem - then I'll merge

**Comment by agross** [comment] 2020-11-04 11:46
Looking good!

**Closed** 2020-11-04 12:07 UTC
