### ISSUE TITLE
Symbole im dunklen Modus nur noch sehr schlecht zu erkennen

### ISSUE THREAD

**Issue by ihavenonick** [ioBroker/ioBroker.javascript#206] opened 2018-12-02 08:56 UTC
![grafik](https://user-images.githubusercontent.com/36501310/49337762-912b9280-f618-11e8-92e3-95e0c50ebfb8.png)

**Comment by AlCalzone** [comment] 2018-12-03 15:53
Duplicate of #222
(Marking this as a duplicate because the other issue has one more detail)

**Comment by GermanBluefox** [comment] 2018-12-04 22:41
Fixed in 4.0.2

**Closed** 2018-12-05 15:59 UTC
Labels: duplicate, fixed
