### ISSUE TITLE
permissions denied when moving scripts in Admin-UI

### ISSUE THREAD

**Issue by zokkai** [ioBroker/ioBroker.javascript#1150] opened 2022-09-29 05:59 UTC
When I try to move scripts in iob-admin I get an permission denied error.
I uses to work a couple of month ago.
I dont know what I changed here to fall into this problem now.

 iob admin v6.2.22
javascript adapter 5.8.10

npm 6.14.17
node / nodejs 14.20.0

permissions on /opt/iobroker/iobroker-data/

drwxrwxr-x+   8 iobroker 4,0K Mai  8  2021 ..
-rw-rwxr--+   1 iobroker 2,4K Mai  8  2021 iobroker.json
drwxrwxr-x+  21 iobroker 4,0K Mai  8  2021 .
drwxrwxr-x+   2 iobroker 4,0K Mai  8  2021 backup-objects
drwxrwxr-x+ 119 iobroker 4,0K Mai  8  2021 files
-rw-rwxr--+   1 iobroker    3 Mai  8  2021 notifications.json
-rw-rwxr--+   1 iobroker  12M Mai  8  2021 states.json.bak
drwxrwxr-x+   2 iobroker 4,0K Mai  8  2021 letsencrypt
-rw-rwxr--+   1 iobroker  12M Mai  8  2021 states.json
drwxrwxr-x+   2 iobroker 4,0K Mai  8  2021 sayit
drwxrwxr-x+   2 iobroker 4,0K Mai  9  2021 lgtv_0
drwxrwxr-x+   2 iobroker  12K Mai  9  2021 sonosCache
drwxrwxr-x+   4 iobroker 4,0K Mai  9  2021 tmp
drwxrwxr-x+   2 iobroker  12K Mai 11  2021 zigbee_2
drwxrwxr-x+   3 iobroker 4,0K Jun  7  2021 history
drwxrwxr-x+   2 iobroker 4,0K Jun  7  2021 0
drwxrwxr-x+   4 iobroker 4,0K Jul 15  2021 tuya_0
-rw-rwxr--+   1 iobroker    0 Aug 12  2021 objects.json.broken
drwxrwxr-x+   4 iobroker 4,0K Dez 25  2021 node-red
drwxrwxr-x+   2 iobroker 4,0K Dez 25  2021 homekit-controller.0
drwxrwxr-x+   2 iobroker 4,0K Jan 19  2022 zigbee_3
drwxrwxr-x+   2 iobroker 4,0K Jan 20  2022 zigbee_4
drwxrwxr-x+   2 iobroker 4,0K Feb 24  2022 backitup
-rw-rwxr--+   1 iobroker  19M Mär 12  2022 objects.json.bak.migrated
-rw-rwxr--+   1 iobroker  19M Mär 12  2022 objects.json.migrated
drwxrwxr-x+   2 iobroker 4,0K Jun  6 13:31 telegram_0
drwxrwxr-x+   2 iobroker 4,0K Jun  6 13:31 telegram_1
-rw-rw-r--+   1 iobroker  50M Sep 26 11:35 objects.jsonl
drwxrwxr-x+   2 iobroker 4,0K Sep 29 07:56 objects.jsonl.lock

![image](https://user-images.githubusercontent.com/49320831/192950968-bca27660-4c6f-4e45-9029-5506ecc339c5.png)

What goes wrong?
 
TIA Kai

**Comment by klein0r** [comment] 2022-10-04 13:37
As "moving" means deletion + creation, this is maybe a duplicate of #1151

**Comment by Apollon77** [comment] 2022-10-24 14:39
Fixed by Admin 6.2.23

**Closed by Apollon77** 2022-10-24 14:39 UTC
Labels: bug
